---
- name: Download the Go tarball
  get_url:
    url: https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
    dest: /usr/local/src/go1.16.5.linux-amd64.tar.gz
    checksum: sha256:b12c23023b68de22f74c0524f10b753e7b08b1504cb7e417eccebdd3fae49061

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
  when: go_version is failed or go_version.stdout != "go version go1.16.5 linux/amd64"

- name: Extract the Go tarball
  unarchive:
    src: /usr/local/src/go1.16.5.linux-amd64.tar.gz
    dest: /usr/local
    copy: no
  when: go_version or failed or go_version.stdout != go_version_target

- name: Add the Go bin directory to the PATH environment variable for all users
  copy:
    src: go-bin.sh
    dest: /etc/profile.d

- name: Set GOPATH for all users
  copy:
    src: go-path.sh
    dest: /etc/profile.d

- name: Sourcing GO BIN
  command: bash -c 'source /etc/profile.d/go-bin.sh'

- name: Sourcing GOPATH
  command: bash -c 'source /etc/profile.d/go-path.sh'